include: '../config.py'

rule all:
    input:
        KALLISTO,
        HISAT,
        SAMTOOLS,
        FEATURE_COUNTS,
        SEQTK,

        'versions.html'

rule get_versions:
    output:
        'versions.html'
    shell:
        source_rmd('.', 'versions.Rmd')

rule get_kallisto:
    output:
        KALLISTO
    params:
        url = 'https://github.com/pachterlab/kallisto/releases/download/v0.42.4/kallisto_linux-v0.42.4.tar.gz',
        tmp = 'kallisto_linux'
    shell:
        'wget -O kallisto_binary.tar.gz {params.url}; '
        'tar -xf kallisto_binary.tar.gz; '
        'mv kallisto_linux-* {params.tmp}; '
        'find {params.tmp} -perm /111 -type f -exec cp {{}} bin \;'
        ' && '
        'rm -rf {params.tmp} kallisto*'

rule get_samtools:
    output:
        SAMTOOLS
    params:
        url = 'https://github.com/samtools/samtools/releases/download/1.3/samtools-1.3.tar.bz2',
        tmp = 'samtools'
    shell:
        'wget -O {params.tmp}.tar.gz {params.url}'
        ' && '
        'tar -xf {params.tmp}.tar.gz'
        ' && '
        'cd {params.tmp}-*'
        ' && '
        'make prefix=.. install'
        ' && '
        'rm -rf {params.tmp}*'


rule get_hisat:
    output:
        HISAT
    params:
        url = 'ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/downloads/hisat2-2.0.1-beta-Linux_x86_64.zip'
    shell:
        'wget -O hisat2.zip {params.url}'
        ' && '
        'unzip hisat2.zip'
        ' && '
        'find hisat2* -perm /111 -type f -exec cp {{}} bin \;'
        ' && '
        'rm -rf hisat2*'

rule get_feature_counts:
    output:
        FEATURE_COUNTS
    params:
        url = 'http://downloads.sourceforge.net/project/subread/subread-1.5.0-p1/subread-1.5.0-p1-Linux-x86_64.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fsubread%2Ffiles%2Fsubread-1.5.0-p1%2F&ts=1456431207&use_mirror=iweb'
    shell:
        'wget -O subread.tar.gz "{params.url}"'
        ' && '
        'tar -xf subread.tar.gz'
        ' && '
        'cp -rf subread*/bin/* bin'
        ' && '
        'rm -rf subread*'

rule get_seqtk:
    output:
        SEQTK
    params:
        url = 'https://github.com/lh3/seqtk',
        tmp = 'seqtk',
        branch = '4feb6e81444ab6bc44139dd3a125068f81ae4ad8'
    shell:
        'git clone {params.url} {params.tmp};'
        ' git reset --hard {params.branch};'
        # 'git clone --branch {params.branch} --depth 1 {params.url} {params.tmp};'
        ' cd {params.tmp};'
        ' make;'
        ' cd ..;'
        # 'find {params.tmp} -maxdepth 1 -perm +o+x -type f -exec cp {{}} bin \;'
        ' find {params.tmp} -maxdepth 1 -perm /111 -type f -exec cp {{}} bin \;'
        ' && '
        ' rm -rf {params.tmp}'
