include: '../config.py'

rule all:
    input:
        KALLISTO,
        SALMON,
        SAMTOOLS,
        OPENSSL,
        PANDOC,
        'r_pkg_install_success.txt',
        'versions.html'

rule get_versions:
    input:
        'r_pkg_install_success.txt'
    output:
        'versions.html'
    shell:
        source_rmd('.', 'versions.Rmd')

rule get_r_pkgs:
   input:
        OPENSSL
    output:
        'r_pkg_install_success.txt'
    shell:
        source_r('.', 'r_pkg_install.R')

rule get_kallisto:
    output:
        KALLISTO
    params:
        url = 'https://github.com/pachterlab/kallisto/releases/download/v0.44.0/kallisto_linux-v0.44.0.tar.gz',
        tmp = 'kallisto_linux'
    shell:
        'wget -O kallisto_binary.tar.gz {params.url}; '
        'tar -xf kallisto_binary.tar.gz; '
        'mv kallisto_linux-* {params.tmp}; '
        'find {params.tmp} -perm /111 -type f -exec cp {{}} bin \;'
        ' && '
        'rm -rf {params.tmp} kallisto*'

rule get_salmon:
    output:
        SALMON
    params:
        url = 'https://github.com/COMBINE-lab/salmon/releases/download/v0.9.1/Salmon-0.9.1_linux_x86_64.tar.gz',
        tmp = 'salmon_linux'
    shell:
        'wget -O salmon_binary.tar.gz {params.url}; '
        'tar -xf salmon_binary.tar.gz; '
        'mv Salmon* {params.tmp}; '
        'cp -r {params.tmp}/lib .; '
        'cp -r {params.tmp}/bin/* bin; '
        'rm -rf {params.tmp} salmon* Salmon*'

rule get_samtools:
    output:
        SAMTOOLS
    params:
        url = 'https://github.com/samtools/samtools/releases/download/1.3/samtools-1.3.tar.bz2',
        tmp = 'samtools'
    shell:
        'wget -O {params.tmp}.tar.gz {params.url}'
        ' && '
        'tar -xf {params.tmp}.tar.gz'
        ' && '
        'cd {params.tmp}-*'
        ' && '
        'make prefix=.. install'
        ' && '
        'rm -rf {params.tmp}*'

rule get_pandoc:
    output:
        PANDOC
    params:
        url = 'https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-linux.tar.gz'
    shell:
        'wget {params.url}; mkdir tmp; '
        'tar xvzf pandoc-2.1.1-linux.tar.gz --strip-components 1 -C tmp; '
        'mv tmp/share .; mv tmp/bin/* bin/; '
        'rm -r tmp/; '
        'rm pandoc-2.1.1-linux.tar.gz'

rule get_openssl:
    output:
        OPENSSL
    params:
        url = 'https://www.openssl.org/source/openssl-1.1.0h.tar.gz'
    shell:
        'wget {params.url}; mkdir tmp; mkdir local'
        'tar xvzf openssl-1.1.0h.tar.gz --strip-components 1 -C tmp; '
        'cd tmp; ./config --prefix={LOCAL} --openssldir={LOCAL}/ssl;'
        'make; make test; make install; cd ..; rm -r tmp/ openssl-1.1.0h.tar.gz'
